/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import processing.core.PApplet;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void simpleTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }

    @Test
    public void testForApp(){
        App app = new App();
        PApplet.runSketch(new String[] {"App"}, app);
        app.delay(1000); 
        app.noLoop();
    }

    
}
